name: google_places_api_flutter
description: Flutter package for integrating Google Places API into your Flutter apps, offering real-time autocomplete suggestions, place details, and more.
version: 2.0.0
homepage: https://github.com/mhdaslam790/google_places_api_flutter.git

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  google_api_headers: ^4.2.0
  logger: ^2.4.0
   

dev_dependencies:
  flutter_test:
    sdk: flutter
 

license: MIT 

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
